import { TRPCError } from "@trpc/server";
import { nanoid } from "nanoid";
import { z } from "zod";
import { createDylibBuild, getDylibBuildsByOwner, getDylibBuildsByPackage, getPackageById, logActivity } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import fs from "fs/promises";
import path from "path";

function generateDylibContent(pkg: { name: string; token: string; version: string }): Buffer {
  const content = `
// ============================================================
//  API Server Dylib — Generated by API Server Manager
//  Package: ${pkg.name}
//  Version: ${pkg.version}
//  Token:   ${pkg.token}
//  Generated: ${new Date().toISOString()}
// ============================================================
//
//  INSTRUÇÕES DE USO:
//  1. Injete este arquivo .dylib no seu IPA usando um tool de injeção
//  2. O dylib irá conectar automaticamente na API Server usando o token acima
//  3. Na inicialização do app, o SDK irá:
//     a) Solicitar o UDID do dispositivo (botão "Get UDID")
//     b) Registrar o device na API Server
//     c) Exibir tela de login pedindo a Key de acesso
//  4. Após inserir uma Key válida, o usuário terá acesso ao conteúdo
//
//  FORMATO DAS KEYS:
//  [ALIAS]-[DURATION]-[UNIQUE_CODE]
//  Exemplo: APISERVER-MONTH-ABC123XYZ456
//
//  DURAÇÕES DISPONÍVEIS:
//  - DAY   → 1 dia
//  - WEEK  → 7 dias
//  - MONTH → 30 dias
//  - YEAR  → 365 dias
//
//  CONFIGURAÇÃO INTERNA (NÃO EDITAR):
//  API_TOKEN = "${pkg.token}"
//  PACKAGE_NAME = "${pkg.name}"
//  PACKAGE_VERSION = "${pkg.version}"
//  API_ENDPOINT = "https://api.apiserver.manager/v1"
//
//  © Ruan Dev — Todos os direitos reservados
// ============================================================

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

static NSString *const kAPIToken = @"${pkg.token}";
static NSString *const kPackageName = @"${pkg.name}";
static NSString *const kPackageVersion = @"${pkg.version}";
static NSString *const kAPIEndpoint = @"https://api.apiserver.manager/v1";

@interface APIServerSDK : NSObject
+ (instancetype)sharedInstance;
- (void)initializeWithToken:(NSString *)token;
- (void)requestUDID;
- (void)validateKey:(NSString *)key completion:(void(^)(BOOL valid, NSDictionary *info))completion;
@end

@implementation APIServerSDK

+ (instancetype)sharedInstance {
    static APIServerSDK *instance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        instance = [[APIServerSDK alloc] init];
    });
    return instance;
}

- (void)initializeWithToken:(NSString *)token {
    NSLog(@"[APIServer] Inicializando SDK — Package: %@", kPackageName);
    NSLog(@"[APIServer] Token: %@", token);
    [self checkDeviceRegistration];
}

- (void)checkDeviceRegistration {
    NSString *udid = [self getStoredUDID];
    if (!udid) {
        [self showGetUDIDScreen];
    } else {
        [self registerDevice:udid];
    }
}

- (NSString *)getStoredUDID {
    return [[NSUserDefaults standardUserDefaults] stringForKey:@"com.apiserver.udid"];
}

- (void)showGetUDIDScreen {
    NSLog(@"[APIServer] Exibindo tela de obtenção de UDID");
    // Implementação da tela de Get UDID
}

- (void)registerDevice:(NSString *)udid {
    NSLog(@"[APIServer] Registrando device: %@", udid);
    // Chamada para API de registro de device
}

- (void)validateKey:(NSString *)key completion:(void(^)(BOOL valid, NSDictionary *info))completion {
    NSLog(@"[APIServer] Validando key: %@", key);
    // Chamada para API de validação de key
}

@end

// Auto-inicialização
__attribute__((constructor))
static void APIServerInit(void) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [[APIServerSDK sharedInstance] initializeWithToken:kAPIToken];
    });
}
`;
  return Buffer.from(content, "utf-8");
}

export const dylibRouter = router({
  generate: protectedProcedure
    .input(z.object({
      packageId: z.number(),
      version: z.string().default("1.0.0"),
    }))
    .mutation(async ({ ctx, input }) => {
      const pkg = await getPackageById(input.packageId);
      if (!pkg) throw new TRPCError({ code: "NOT_FOUND", message: "Package não encontrado" });
      if (ctx.user.role !== "admin" && pkg.ownerId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN" });

      const content = generateDylibContent({ name: pkg.name, token: pkg.token, version: input.version });
      const fileName = `${pkg.name.replace(/\s+/g, "_")}_v${input.version}_${nanoid(6)}.dylib`;
      
      // Salvar localmente na pasta public para download direto
      // Em produção, o diretório estático é dist/public
      const publicDir = process.env.NODE_ENV === "production" 
        ? path.join(process.cwd(), "dist", "public", "builds")
        : path.join(process.cwd(), "client", "public", "builds");
      
      await fs.mkdir(publicDir, { recursive: true });
      const filePath = path.join(publicDir, fileName);
      await fs.writeFile(filePath, content);

      const downloadUrl = `/builds/${fileName}`;

      await createDylibBuild({
        packageId: input.packageId,
        ownerId: ctx.user.id,
        fileName,
        s3Url: downloadUrl,
        s3Key: fileName,
        version: input.version,
        sizeBytes: content.length,
      });

      await logActivity({
        userId: ctx.user.id,
        action: "generate_dylib",
        details: `Package: ${pkg.name} v${input.version}`,
        entityType: "dylib",
      });

      return { success: true, fileName, downloadUrl };
    }),

  history: protectedProcedure
    .input(z.object({ packageId: z.number().optional() }))
    .query(async ({ ctx, input }) => {
      if (input.packageId) return getDylibBuildsByPackage(input.packageId);
      return getDylibBuildsByOwner(ctx.user.id);
    }),
});
