import { TRPCError } from "@trpc/server";
import { nanoid } from "nanoid";
import { z } from "zod";
import { createDylibBuild, getDylibBuildsByOwner, getDylibBuildsByPackage, getPackageById, logActivity } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import fs from "fs/promises";
import path from "path";

function generateDylibContent(pkg: { name: string; token: string; version: string }): Buffer {
  const content = `
// ============================================================
//  API Server Dylib — Generated by API Server Manager
//  Package: \${pkg.name}
//  Version: \${pkg.version}
//  Token:   \${pkg.token}
//  Generated: \${new Date().toISOString()}
// ============================================================

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <objc/runtime.h>

static NSString *const kAPIToken = @"\${pkg.token}";
static NSString *const kPackageName = @"\${pkg.name}";
static NSString *const kPackageVersion = @"\${pkg.version}";
static NSString *const kAPIEndpoint = @"https://apiserver-manager-v2-production.up.railway.app";
static const NSInteger kKeyValidationTimeout = 30; // 30 segundos

@interface APIServerSDK : NSObject
+ (instancetype)sharedInstance;
- (void)initialize;
@end

@implementation APIServerSDK

+ (instancetype)sharedInstance {
    static APIServerSDK *instance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        instance = [[APIServerSDK alloc] init];
    });
    return instance;
}

- (void)initialize {
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self checkActivation];
    });
}

- (void)checkActivation {
    NSString *udid = [[NSUserDefaults standardUserDefaults] stringForKey:@"com.apiserver.udid"];
    if (!udid) {
        [self showGetUDIDScreen];
    } else {
        [self showKeyValidationScreen];
    }
}

- (void)showGetUDIDScreen {
    UIViewController *root = [UIApplication sharedApplication].keyWindow.rootViewController;
    UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Ativação Necessária"
        message:@"Seu dispositivo não está registrado. Clique abaixo para obter seu UDID."
        preferredStyle:UIAlertControllerStyleAlert];
    
    [alert addAction:[UIAlertAction actionWithTitle:@"Copiar UDID" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
        NSString *generatedUDID = [[[UIDevice currentDevice] identifierForVendor] UUIDString];
        [[UIPasteboard generalPasteboard] setString:generatedUDID];
        [[NSUserDefaults standardUserDefaults] setObject:generatedUDID forKey:@"com.apiserver.udid"];
        
        // Registrar o UDID no servidor
        [self registerDeviceOnServer:generatedUDID];
        
        // Fechar o alerta atual e exibir a tela de validação de Key imediatamente
        [alert dismissViewControllerAnimated:YES completion:^{
            [self showKeyValidationScreen];
        }];
    }];
    
    [root presentViewController:alert animated:YES completion:nil];
}

- (void)showKeyValidationScreen {
    UIViewController *root = [UIApplication sharedApplication].keyWindow.rootViewController;
    
    // Aguardar um pouco para garantir que o alerta anterior foi fechado
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Validar Acesso"
            message:@"Cole sua chave de acesso aqui. Você tem 30 segundos para validar."
            preferredStyle:UIAlertControllerStyleAlert];
        
        [alert addTextFieldWithConfigurationHandler:^(UITextField * _Nonnull textField) {
            textField.placeholder = @"Cole a chave aqui";
            textField.secureTextEntry = NO;
        }];
        
        // Iniciar o timeout de 30 segundos
        __block NSTimer *timeoutTimer = [NSTimer scheduledTimerWithTimeInterval:kKeyValidationTimeout repeats:NO block:^(NSTimer * _Nonnull timer) {
            // Se o timeout expirar, fechar o app
            [self closeApplication];
        }];
    
        [alert addAction:[UIAlertAction actionWithTitle:@"Validar" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
            // Cancelar o timer ao validar
            [timeoutTimer invalidate];
            
            UITextField *keyField = alert.textFields.firstObject;
            NSString *enteredKey = keyField.text;
            
            if (enteredKey && enteredKey.length > 0) {
                [self validateKey:enteredKey];
            } else {
                UIAlertController *errorAlert = [UIAlertController alertControllerWithTitle:@"Erro"
                    message:@"Por favor, insira uma chave válida."
                    preferredStyle:UIAlertControllerStyleAlert];
                
                [errorAlert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                    [self showKeyValidationScreen];
                }]];
                
                [root presentViewController:errorAlert animated:YES completion:nil];
            }
        }]];
        
        [alert addAction:[UIAlertAction actionWithTitle:@"Cancelar" style:UIAlertActionStyleCancel handler:^(UIAlertAction * _Nonnull action) {
            [timeoutTimer invalidate];
            [self closeApplication];
        }]];
        
        [root presentViewController:alert animated:YES completion:nil];
    });
}

- (void)validateKey:(NSString *)key {
    NSString *udid = [[NSUserDefaults standardUserDefaults] stringForKey:@"com.apiserver.udid"];
    
    // Fazer requisição para validar a key no servidor
    NSString *urlString = [NSString stringWithFormat:@"%@/trpc/publicApi.validateKey", kAPIEndpoint];
    NSURL *url = [NSURL URLWithString:urlString];
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    request.HTTPMethod = @"POST";
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    
    NSDictionary *body = @{
        @"token": kAPIToken,
        @"udid": udid,
        @"key": key
    };
    
    NSError *error = nil;
    request.HTTPBody = [NSJSONSerialization dataWithJSONObject:body options:0 error:&error];
    
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                [self showKeyValidationScreen];
                return;
            }
            
            NSError *jsonError = nil;
            NSDictionary *responseDict = [NSJSONSerialization JSONObjectWithData:data options:0 error:&jsonError];
            
            if (responseDict[@"valid"] && [responseDict[@"valid"] boolValue]) {
                // Key válida - liberar acesso
                [[NSUserDefaults standardUserDefaults] setObject:key forKey:@"com.apiserver.key"];
                [[NSUserDefaults standardUserDefaults] setObject:[NSDate date] forKey:@"com.apiserver.key_validated_at"];
                
                UIAlertController *successAlert = [UIAlertController alertControllerWithTitle:@"Sucesso"
                    message:@"Acesso liberado! Bem-vindo."
                    preferredStyle:UIAlertControllerStyleAlert];
                
                [successAlert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
                
                [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:successAlert animated:YES completion:nil];
            } else {
                // Key inválida
                UIAlertController *errorAlert = [UIAlertController alertControllerWithTitle:@"Erro"
                    message:@"Chave inválida. Tente novamente."
                    preferredStyle:UIAlertControllerStyleAlert];
                
                [errorAlert addAction:[UIAlertAction actionWithTitle:@"Tentar Novamente" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                    [self showKeyValidationScreen];
                }]];
                
                [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:errorAlert animated:YES completion:nil];
            }
        });
    }];
    
    [task resume];
}

- (void)registerDeviceOnServer:(NSString *)udid {
    // Fazer requisição para registrar o device no servidor
    NSString *urlString = [NSString stringWithFormat:@"%@/trpc/publicApi.registerDevice", kAPIEndpoint];
    NSURL *url = [NSURL URLWithString:urlString];
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    request.HTTPMethod = @"POST";
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    
    NSDictionary *body = @{
        @"token": kAPIToken,
        @"udid": udid,
        @"name": [NSString stringWithFormat:@"Device %@", [udid substringToIndex:8]]
    };
    
    NSError *error = nil;
    request.HTTPBody = [NSJSONSerialization dataWithJSONObject:body options:0 error:&error];
    
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        if (!error) {
            NSLog(@"[APIServer] Device registrado com sucesso: %@", udid);
        } else {
            NSLog(@"[APIServer] Erro ao registrar device: %@", error.localizedDescription);
        }
    }];
    
    [task resume];
}

- (void)closeApplication {
    // Encerrar o app após o timeout
    exit(0);
}

@end

// Auto-inicialização
__attribute__((constructor))
static void APIServerInit(void) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [[APIServerSDK sharedInstance] initialize];
    });
}
`;

  return Buffer.from(content, 'utf8');
}

export const dylibRouter = router({
  buildDylib: protectedProcedure
    .input(z.object({ packageId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const pkg = await getPackageById(input.packageId);
      
      if (!pkg) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Package not found",
        });
      }

      if (pkg.ownerId !== ctx.userId) {
        throw new TRPCError({
          code: "UNAUTHORIZED",
          message: "You don't have permission to build this package",
        });
      }

      const buildId = nanoid();
      const dylibContent = generateDylibContent({
        name: pkg.name,
        token: pkg.token,
        version: pkg.version,
      });

      const downloadDir = path.join(process.cwd(), "client/dist/downloads");
      const fileName = `${pkg.name}_v${pkg.version}_${buildId}.dylib`;
      const filePath = path.join(downloadDir, fileName);

      try {
        await fs.mkdir(downloadDir, { recursive: true });
        await fs.writeFile(filePath, dylibContent);

        await createDylibBuild({
          id: buildId,
          packageId: input.packageId,
          ownerId: ctx.userId,
          fileName,
          downloadUrl: `/downloads/${fileName}`,
        });

        await logActivity({
          userId: ctx.userId,
          action: "BUILD_DYLIB",
          packageId: input.packageId,
          details: `Built dylib: ${fileName}`,
        });

        return {
          success: true,
          fileName,
          downloadUrl: `/downloads/${fileName}`,
          buildId,
        };
      } catch (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to build dylib",
        });
      }
    }),

  getDylibBuilds: protectedProcedure
    .input(z.object({ packageId: z.string().optional() }))
    .query(async ({ ctx, input }) => {
      if (input.packageId) {
        return await getDylibBuildsByPackage(input.packageId);
      }
      return await getDylibBuildsByOwner(ctx.userId);
    }),
});
